# Generated by Django 3.0.6 on 2020-11-29 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=4000)),
                ('order', models.IntegerField()),
                ('given_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='given_by', to=settings.AUTH_USER_MODEL)),
                ('wanted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wanted_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
