# Generated by Django 3.0.6 on 2020-11-29 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0002_gift'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='wishlist.Group'),
            preserve_default=False,
        ),
    ]
